spring.application.name=api

# ==============================================================================
# DATASOURCE - Supabase / PostgreSQL (Pooler IPv4)
# ==============================================================================
spring.datasource.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.ppkejrnppfuatarenrls
spring.datasource.password=Contrase\u00F1aProyectoInterfaces
spring.datasource.driver-class-name=org.postgresql.Driver

# SSL requerido por Supabase y optimización del pool
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.data-source-properties.sslmode=require
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# ==============================================================================
# JPA / HIBERNATE
# ==============================================================================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8082